name: push to version tag
on:
  push:
    tags:
      - v*

jobs:
  Build_tox:
    runs-on: [self-hosted, Windows, TouchDesigner]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: true 

      - name: SudoMagic TD Package Builder
        uses: SudoMagicCode/action-build-td-tox-package@v0.0.2
        with:
          build_settings: ./buildSettings.json

          
      - name: Release
        uses:  softprops/action-gh-release@v2.2.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./release/package.zip